### ISSUE TITLE
Recommend HEX 607641 and HEX F5BB54 for brasilian flag plots

### ISSUE THREAD

**Issue by lenzip** [ttedeschi/tutorial_CAT#1]
Please remove the old kOrange, kGreen+1 recommendations and only stick to these HEX codes

**Comment by lenzip** [comment]
Also, the green and yellow here are inverted.
![image](https://github.com/ttedeschi/tutorial_CAT/assets/4907094/9e32e17b-2408-42ec-ade8-eb7435700900)

**Comment by ttedeschi** [comment]
Solved in https://github.com/ttedeschi/tutorial_CAT/commit/6df8be385e971468f6953e67ec24c8022560b64f
